# Generated by Django 3.1.5 on 2021-05-29 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Προφίλ Χρηστών',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.profile')),
                ('postgrad_program', models.CharField(choices=[('Κατεύθυνση 1η: Τεχνολογίες και Εφαρμογές Ιστού', 'Κατεύθυνση 1η: Τεχνολογίες και Εφαρμογές Ιστού'), ('Κατεύθυνση 2η: Διαχείριση Δικτύων Επικοινωνιών και Υπηρεσιών Επόμενης Γενιάς', 'Κατεύθυνση 2η: Διαχείριση Δικτύων Επικοινωνιών και Υπηρεσιών Επόμενης Γενιάς'), ('Κατεύθυνση 3η: Πληροφοριακά Συστήματα στη Διοίκηση Επιχειρήσεων', 'Κατεύθυνση 3η: Πληροφοριακά Συστήματα στη Διοίκηση Επιχειρήσεων')], max_length=80, null=True)),
                ('program_duration', models.CharField(choices=[('Πλήρης Φοίτηση', 'Πλήρης Φοίτηση'), ('Μερική Φοίτηση', 'Μερική Φοίτηση')], max_length=14, null=True)),
            ],
            options={
                'verbose_name': 'Φοιτητής',
                'verbose_name_plural': 'Φοιτητές',
            },
        ),
    ]
