# Generated by Django 3.1.5 on 2021-06-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_postgrad_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='postgrad_year',
            field=models.IntegerField(blank=True, choices=[(2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, null=True),
        ),
    ]
