# Generated by Django 3.1.5 on 2021-06-27 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210607_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Προφίλ Χρήστη', 'verbose_name_plural': 'Προφίλ Χρηστών'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Τμήμα'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστη'),
        ),
        migrations.AlterField(
            model_name='student',
            name='postgrad_program',
            field=models.CharField(choices=[('Κατεύθυνση 1η: Τεχνολογίες και Εφαρμογές Ιστού', 'Κατεύθυνση 1η: Τεχνολογίες και Εφαρμογές Ιστού'), ('Κατεύθυνση 2η: Διαχείριση Δικτύων Επικοινωνιών και Υπηρεσιών Επόμενης Γενιάς', 'Κατεύθυνση 2η: Διαχείριση Δικτύων Επικοινωνιών και Υπηρεσιών Επόμενης Γενιάς'), ('Κατεύθυνση 3η: Πληροφοριακά Συστήματα στη Διοίκηση Επιχειρήσεων', 'Κατεύθυνση 3η: Πληροφοριακά Συστήματα στη Διοίκηση Επιχειρήσεων')], max_length=80, null=True, verbose_name='Μεταπτυχιακό Πρόγραμμα'),
        ),
        migrations.AlterField(
            model_name='student',
            name='postgrad_year',
            field=models.IntegerField(blank=True, choices=[(2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, null=True, verbose_name='Έτος Εγγραφής'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.profile', verbose_name='Προφίλ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program_duration',
            field=models.CharField(choices=[('Πλήρης Φοίτηση', 'Πλήρης Φοίτηση'), ('Μερική Φοίτηση', 'Μερική Φοίτηση')], max_length=14, null=True, verbose_name='Διάρκεια Σπουδών'),
        ),
    ]
