# Generated by Django 3.1.5 on 2021-04-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210126_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.profile')),
                ('postgrad_program', models.CharField(max_length=200, null=True)),
                ('year', models.DateField()),
                ('program_duration', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time')], default='FT', max_length=2)),
            ],
        ),
    ]
