# Generated by Django 3.1.5 on 2021-04-04 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='year',
        ),
    ]
