# Generated by Django 3.1.5 on 2021-06-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Ανακοίνωση', 'verbose_name_plural': 'Ανακοινώσεις'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(max_length=4000),
        ),
    ]
