# Generated by Django 3.1.5 on 2021-05-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_auto_20210508_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speechrequisition',
            old_name='timestamp',
            new_name='date',
        ),
    ]
