# Generated by Django 3.1.5 on 2021-05-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_auto_20210508_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingrequisition',
            options={'verbose_name': 'Αίτηση Χρηματοδότησης', 'verbose_name_plural': 'Αιτήσεις Χρηματοδότησης'},
        ),
        migrations.AlterModelOptions(
            name='speechrequisition',
            options={'verbose_name': 'Αίτηση Εκδήλωσης', 'verbose_name_plural': 'Αιτήσεις Εκδήλωσης'},
        ),
    ]
