# Generated by Django 3.1.5 on 2021-06-06 15:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professor', '0005_auto_20210526_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrequisition',
            name='status',
            field=models.CharField(choices=[('Αποδεκτή', 'Αποδεκτή'), ('Μη Αποδεκτή', 'Μη Αποδεκτή'), ('Υπο Έλεγχο', 'Υπο Έλεγχο')], default='Υπο Έλεγχο', max_length=20),
        ),
        migrations.AlterField(
            model_name='speechrequisition',
            name='status',
            field=models.CharField(choices=[('Αποδεκτή', 'Αποδεκτή'), ('Μη Αποδεκτή', 'Μη Αποδεκτή'), ('Υπο Έλεγχο', 'Υπο Έλεγχο')], default='Υπο Έλεγχο', max_length=20),
        ),
        migrations.CreateModel(
            name='TravelRequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('requested_date', models.DateField()),
                ('description', models.TextField()),
                ('travel_fees', models.DecimalField(decimal_places=1, max_digits=6)),
                ('accommodation_fees', models.DecimalField(decimal_places=1, max_digits=6)),
                ('registration_fees', models.DecimalField(decimal_places=1, max_digits=6)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Αποδεκτή', 'Αποδεκτή'), ('Μη Αποδεκτή', 'Μη Αποδεκτή'), ('Υπο Έλεγχο', 'Υπο Έλεγχο')], default='Υπο Έλεγχο', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Αίτηση Μετακίνησης',
                'verbose_name_plural': 'Αιτήσεις Μετακινήσεων',
            },
        ),
    ]
