# Generated by Django 3.1.5 on 2021-06-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0006_auto_20210606_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechrequisition',
            name='requested_time',
            field=models.TimeField(default='14:30', help_text='Εισάγετε την Ώρα της Ομιλίας/Εκδήλωσης', verbose_name='Αιτούμενη Ώρα'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speechrequisition',
            name='requested_date',
            field=models.DateField(help_text='Εισάγετε την Ημερομηνία της Ομιλίας/Εκδήλωσης', verbose_name='Αιτούμενη Ημερομηνία'),
        ),
    ]
