# Generated by Django 3.1.5 on 2021-06-09 19:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0007_auto_20210609_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrequisition',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='speechrequisition',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='travelrequisition',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
