# Generated by Django 3.1.5 on 2021-06-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0008_auto_20210609_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrequisition',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='speechrequisition',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='travelrequisition',
            name='description',
            field=models.TextField(),
        ),
    ]
