# Generated by Django 3.1.5 on 2021-06-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0009_auto_20210613_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechrequisition',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
