# Generated by Django 3.1.5 on 2021-06-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0010_auto_20210613_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechrequisition',
            name='description',
            field=models.TextField(),
        ),
    ]
