# Generated by Django 3.1.5 on 2021-06-27 15:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professor', '0011_auto_20210613_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingrequisition',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης'),
        ),
        migrations.AlterField(
            model_name='fundingrequisition',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Ποσό'),
        ),
        migrations.AlterField(
            model_name='fundingrequisition',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='fundingrequisition',
            name='description',
            field=models.TextField(verbose_name='Περιγραφή'),
        ),
        migrations.AlterField(
            model_name='fundingrequisition',
            name='status',
            field=models.CharField(choices=[('Αποδεκτή', 'Αποδεκτή'), ('Μη Αποδεκτή', 'Μη Αποδεκτή'), ('Υπο Έλεγχο', 'Υπο Έλεγχο')], default='Υπο Έλεγχο', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='fundingrequisition',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='fundingrequisition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.AlterField(
            model_name='speechrequisition',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='speechrequisition',
            name='description',
            field=models.TextField(verbose_name='Περιγραφή'),
        ),
        migrations.AlterField(
            model_name='speechrequisition',
            name='status',
            field=models.CharField(choices=[('Αποδεκτή', 'Αποδεκτή'), ('Μη Αποδεκτή', 'Μη Αποδεκτή'), ('Υπο Έλεγχο', 'Υπο Έλεγχο')], default='Υπο Έλεγχο', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='speechrequisition',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='speechrequisition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.AlterField(
            model_name='travelrequisition',
            name='accommodation_fees',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Ποσό Διαμονής'),
        ),
        migrations.AlterField(
            model_name='travelrequisition',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='travelrequisition',
            name='description',
            field=models.TextField(verbose_name='Περιγραφή'),
        ),
        migrations.AlterField(
            model_name='travelrequisition',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Τοποθεσία'),
        ),
        migrations.AlterField(
            model_name='travelrequisition',
            name='registration_fees',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Ποσό Εγγραφής'),
        ),
        migrations.AlterField(
            model_name='travelrequisition',
            name='requested_date',
            field=models.DateField(verbose_name='Αιτούμενη Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='travelrequisition',
            name='status',
            field=models.CharField(choices=[('Αποδεκτή', 'Αποδεκτή'), ('Μη Αποδεκτή', 'Μη Αποδεκτή'), ('Υπο Έλεγχο', 'Υπο Έλεγχο')], default='Υπο Έλεγχο', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='travelrequisition',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='travelrequisition',
            name='travel_fees',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Ποσό Ταξιδιού'),
        ),
        migrations.AlterField(
            model_name='travelrequisition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
    ]
