# Generated by Django 3.1.5 on 2021-06-27 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0012_auto_20210627_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundingrequisition',
            old_name='date',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='speechrequisition',
            name='date',
        ),
        migrations.RemoveField(
            model_name='travelrequisition',
            name='date',
        ),
        migrations.AddField(
            model_name='speechrequisition',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AddField(
            model_name='speechrequisition',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης'),
        ),
        migrations.AddField(
            model_name='travelrequisition',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AddField(
            model_name='travelrequisition',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης'),
        ),
    ]
