# Generated by Django 3.1.5 on 2021-05-29 01:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=4)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('program_duration', models.CharField(choices=[('Πλήρης Φοίτηση', 'Πλήρης Φοίτηση'), ('Μερική Φοίτηση', 'Μερική Φοίτηση')], default='Πλήρης Φοίτηση', max_length=14)),
            ],
            options={
                'verbose_name': 'Δόση Μεταπτυχιακού',
                'verbose_name_plural': 'Δόσεις Μεταπτυχιακού',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('document', models.FileField(upload_to=student.models.user_directory_path)),
                ('bank', models.CharField(blank=True, choices=[('Εθνική Τράπεζα', 'Εθνική Τράπεζα'), ('Πειραιώς', 'Πειραιώς'), ('Eurobank', 'Eurobank'), ('Alpha Bank', 'Alpha Bank')], max_length=30)),
                ('transaction_number', models.PositiveIntegerField(blank=True)),
                ('status', models.CharField(choices=[('Αποδεκτή', 'Αποδεκτή'), ('Μη Αποδεκτή', 'Μη Αποδεκτή'), ('Υπο Έλεγχο', 'Υπο Έλεγχο')], default='Υπο Έλεγχο', max_length=20)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.paymentinstallment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Πληρωμή Φοιτητή',
                'verbose_name_plural': 'Πληρωμές Φοιτητών',
            },
        ),
    ]
