# Generated by Django 3.1.5 on 2021-04-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstallments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=4)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
