# Generated by Django 3.1.5 on 2021-04-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentInstallments',
            new_name='PaymentInstallment',
        ),
    ]
