# Generated by Django 3.1.5 on 2021-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210425_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='document',
            field=models.FileField(upload_to='student_payments/%Y/%m/%d/'),
        ),
    ]
